[Bugfix] correctly map USB hardware device paths to the expected integer values in knxd configuration

diff --git a/knxd/rootfs/etc/cont-init.d/2-init-config b/knxd/rootfs/etc/cont-init.d/2-init-config
--- a/knxd/rootfs/etc/cont-init.d/2-init-config
+++ b/knxd/rootfs/etc/cont-init.d/2-init-config
@@ -7,28 +7,61 @@ readonly CONF="/etc/knxd.ini"
 # =======================================
 
 # first check if a custom config is specified and use that
-if bashio::config.has_value 'custom_config' && bashio::config 'custom_config' -ge 5; then
-  echo $(bashio::config 'custom_config') > ${CONF}
-fi;
+if bashio::config.has_value 'custom_config' && [ $(bashio::string.length "$(bashio::config 'custom_config')") > 5 ]; then
+	bashio::log.info "Using custom configuration:"
+	bashio::log.info "$(bashio::config 'custom_config')"
+	echo $(bashio::config 'custom_config') > ${CONF}
+	exit 0
+fi
+
 
 # =======================================
 # auto configuration
 # =======================================
 
 # check if an interface is defined
-if ! bashio::config.has_value 'interface'; then
-	bashio:exit.nok "An interface type needs to be configured"
-fi
-	
-# check if a device is selected, which is mandatory for anything but USB
-if bashio::config.equals 'interface' 'usb' && ! bashio::config.has_value 'device'; then
-	bashio:exit.nok "A device needs to be configured"
+if ! $(bashio::config.has_value 'interface'); then
+	bashio::exit.nok "An interface type needs to be configured"
 fi
 
-# read the config template, replace placeholders and write it back
+# check if a device is selected, which is mandatory for anything but USB
+if $(bashio::config.equals 'interface' 'usb') && ! $(bashio::config.has_value 'device'); then
+	bashio::exit.nok "A device needs to be configured"
+fi
+
+# in case of USB interface, we can not use the device path directly
+# because knxd expects us to pass the bus ID and device ID separately
+# so this is what we do now
+declare USB_DEVICE='';
+declare USB_BUS='';
+declare device=$(bashio::config 'device')
+
+if $(bashio::config.equals 'interface' 'usb') && $(bashio::string.substring "${device}" 0 13) == "/dev/bus/usb/"; then
+	USB_BUS=$(echo "${device}" | cut -d / -f 5 | sed 's/^0*//g')
+	USB_DEVICE=$(echo "${device}" | cut -d / -f 6 | sed 's/^0*//g')
+fi
+
+# replace placeholders and write it back
 sed -i "s|%%INTERFACE%%|$(bashio::config 'interface')|g" "${CONF}"
 sed -i "s|%%DEVICE%%|$(bashio::config 'device')|g" "${CONF}"
 sed -i "s|%%ADDRESS%%|$(bashio::config 'address')|g" "${CONF}"
 sed -i "s|%%CLIENT_ADDRESS%%|$(bashio::config 'client_address')|g" "${CONF}"
 sed -i "s|%%FILTERS%%|$(bashio::config 'usb_filters')|g" "${CONF}"
 sed -i "s|%%DEBUG_ERROR_LEVEL%%|$(bashio::config 'log_error_level')|g" "${CONF}"
+sed -i "s|%%USB_DEVICE%%|${USB_DEVICE}|g" "${CONF}"
+sed -i "s|%%USB_BUS%%|${USB_DEVICE}|g" "${CONF}"
+
+
+# =======================================
+# log output configuration
+# =======================================
+bashio::log.info "Interface:      $(bashio::config 'interface')"
+bashio::log.info "Device:         $(bashio::config 'device')"
+bashio::log.info "Address:        $(bashio::config 'address')"
+bashio::log.info "Client Address: $(bashio::config 'client_address')"
+bashio::log.info "Filters:        $(bashio::config 'usb_filters')"
+bashio::log.info "Log-Level:      $(bashio::config 'log_error_level')"
+if [ "${USB_DEVICE}" != "" ]; then
+        bashio::log.info "USB-Device ID:  ${USB_DEVICE}"
+        bashio::log.info "USB-Bus ID:     ${USB_BUS}"
+fi
